Failure # 1 (occurred at 2023-02-02_11-29-44)
Traceback (most recent call last):
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 593, in start_trial
    return self._start_trial(trial)
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 493, in _start_trial
    runner = self._setup_remote_runner(trial)
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 434, in _setup_remote_runner
    return full_actor_class.remote(**kwargs)
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\actor.py", line 639, in remote
    return actor_cls._remote(args=args, kwargs=kwargs, **updated_options)
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\util\tracing\tracing_helper.py", line 387, in _invocation_actor_class_remote_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\actor.py", line 846, in _remote
    worker.function_actor_manager.export_actor_class(
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\_private\function_manager.py", line 479, in export_actor_class
    check_oversized_function(
  File "C:\Users\matte\AppData\Local\Programs\Python\Python39\lib\site-packages\ray\_private\utils.py", line 810, in check_oversized_function
    raise ValueError(error)
ValueError: The actor ImplicitFunc is too large (154 MiB > FUNCTION_SIZE_ERROR_THRESHOLD=95 MiB). Check that its definition is not implicitly capturing a large array or other object in scope. Tip: use ray.put() to put large objects in the Ray object store.

